### ISSUE TITLE
perf(sbb-datepicker): dateParser gets called too many times

### ISSUE THREAD

**Issue by jeripeierSBB** [sbb-design-systems/lyne-components#1915]
If you select a date in calendar, the dateParser function gets called 4 times. We can improve it to call it fewer times.

**Comment by MarioCastigliano** [comment]
The reason for this is that all satellite components (sbb-datepicker-next-day, sbb-datepicker-previous-day...) listen to the change event to check if any state needs to be updated (e.g. disable arrows). To solve this problem there are two possible approaches: 
- store the valueAsDate inside the datepicker class, so that the parseParser function doesn't get called with every `getValueAsDate`.
- populate the change event detail with a valueAsDate field, so that satellite components don't need to use `getValueAsDate` at all.

Given the low priority and the imperceptible impact on performance, we decided to wait for @kyubisation to discuss this and choose a solution that is in line with the project's common practices.

**Comment by kyubisation** [comment]
I'm tempted to postpone this until our framework migration, with which valueAsDate can be directly used.
